# ansible-playbook -i inventory/opensearch/hosts opensearch_only.yml to test
---
- name: Installation d'OpenSearch
  hosts: opensearch_nodes
  become: true
  gather_facts: true
  roles:
    - opensearch

- name: Installation d'OpenSearch Dashboards
  hosts: opensearch_dashboards_nodes
  become: true
  gather_facts: true
  roles:
    - opensearch_dashboards
