---
- name: Installation de PurpleLab
  hosts: all
  become: yes
  vars:
    db_user: "toor"
    db_pass: "root"
    db_name: "myDatabase"
    encryption_key: "{{ lookup('password', '/dev/null chars=ascii_letters,digits,hexdigits length=32') }}"
    admin_password: "{{ lookup('password', '/dev/null chars=ascii_letters,digits,special length=12') }}"
    ansible_user: "purplelab"

  pre_tasks:
    - name: Vérification de la connexion Internet
      uri:
        url: https://www.google.com
        timeout: 5
      register: internet_check
      failed_when: internet_check.status != 200
      ignore_errors: yes

    - name: Échec en cas d'absence de connexion Internet
      fail:
        msg: "Pas de connexion Internet. Veuillez vous assurer d'avoir une connexion Internet active."
      when: internet_check.status is not defined or internet_check.status != 200

    - name: Vérification de la RAM
      shell: awk '/MemTotal/ {print $2}' /proc/meminfo
      register: ram_info
      changed_when: false

    - name: Vérification de la RAM suffisante
      fail:
        msg: "RAM insuffisante. Un minimum de 7,9 Go de RAM est requis."
      when: (ram_info.stdout | int) < 8000000

    - name: Vérification de la virtualisation matérielle
      shell: grep -E 'vmx|svm' /proc/cpuinfo
      register: virt_check
      changed_when: false
      ignore_errors: yes

    - name: Échec si la virtualisation matérielle est désactivée
      fail:
        msg: "La virtualisation matérielle est désactivée. Veuillez l'activer dans les paramètres BIOS."
      when: virt_check.rc != 0

  roles:
    - common
    - webserver
    - database

- name: Installation d'OpenSearch
  hosts: opensearch_nodes
  become: true
  gather_facts: true
  roles:
    - opensearch

- name: Installation d'OpenSearch Dashboards
  hosts: opensearch_dashboards_nodes
  become: true
  gather_facts: true
  roles:
    - opensearch_dashboards

- name: Suite de l'installation PurpleLab (VirtualBox)
  hosts: all
  become: yes
  roles:
    - virtualbox

  post_tasks:
    - name: Configuration de la VM Windows
      import_tasks: roles/virtualbox/tasks/configure_vm_playbook.yml
      tags: 
        - configure_vm
        - vm_config
      vars:
        ansible_become: no

    - name: Affichage du message final
      debug:
        msg: |
          *********************************************
          *                                           *
          *        PURPLELAB by Krook9d               *
          *                                           *
          *********************************************

          Connect to: http://{{ ansible_default_ipv4.address }}

          The necessary passwords for the application are in admin.txt.
          For better security, change them and harden the server.

    - name: Correction des permissions pour composer
      file:
        path: /var/www/html
        state: directory
        owner: www-data
        group: www-data
        mode: '0775'
        recurse: yes
